# Generated by Django 4.1.1 on 2023-06-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_customuser_profile_picture_alter_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recieved_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
